### ISSUE TITLE
deleting cache without warning intentional?

### ISSUE THREAD

**Issue by thispixel** [Vult-R/RS2-Cache-Library#1]
code in question

`if (file.exists() && file.length() > 0x3200000) {
				file.delete();
			}`

https://github.com/Vult-R/RS2-Cache-Library/blob/master/src/org/rs2cl/Cache.java#L65-L67

is this intentional?

**Comment by Vult-R** [comment]
Fixed. That was not intentional, in a default #317 deob you can see that method in the SignLink class in the #run method.
